### ISSUE TITLE
build_multigraph中的数据源

### ISSUE THREAD

**Issue by xbdx-ipmi** [johnny12150/DySAT_python3#3]
妳好，請問方便提供bulid_multigraph中的#diginetica = 'F:/data/dataset-train-diginetica/train-item-views.csv'，yoochose = 'F:/data/yoochoose-data/yoochoose-clicks.dat'#這兩個數據源嗎？謝謝。

**Comment by xbdx-ipmi** [comment]
@johnny12150

**Comment by johnny12150** [comment]
I used `bulid_multigraph.py` for the other datasets, those datasets could be found at the links below.
- https://2015.recsyschallenge.com/challenge.html
- https://competitions.codalab.org/competitions/11161

**Edit**
Since the original code didn't offer the preprocess code.

**Comment by xbdx-ipmi** [comment]
Thank you very much and wish you all the best.
